operators = {"+": lambda x, y: (x+y,),
             "-": lambda x, y: (x - y,),
             "*": lambda x, y: (x * y,),
             "/": lambda x, y: (x / y,),
             "mod": lambda x, y: (x % y,),
             "and": lambda x, y: (x and y,),
             "or": lambda x, y: (x or y,),
             "not": lambda x: (not x,),
             "xor": lambda x, y: (x ^ y,),
             "==": lambda x, y: (x == y,),
             "!=": lambda x, y: (x != y,),
             "<=": lambda x, y: (x <= y,),
             ">=": lambda x, y: (x >= y,),
             "<": lambda x, y: (x < y,),
             ">": lambda x, y: (x < y,),
}
